CREATE DATABASE [blogengine_db]
GO
ALTER DATABASE [blogengine_db] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [blogengine_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [blogengine_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [blogengine_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [blogengine_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [blogengine_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [blogengine_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [blogengine_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [blogengine_db] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [blogengine_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [blogengine_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [blogengine_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [blogengine_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [blogengine_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [blogengine_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [blogengine_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [blogengine_db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [blogengine_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [blogengine_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [blogengine_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [blogengine_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [blogengine_db] SET  READ_WRITE 
GO
ALTER DATABASE [blogengine_db] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [blogengine_db] SET  MULTI_USER 
GO
ALTER DATABASE [blogengine_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [blogengine_db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [blogengine_db] SET DELAYED_DURABILITY = DISABLED 
GO
USE [blogengine_db]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [blogengine_db] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
